#!/usr/bin/env node
/*
 * Points the product at one Nucleo family.
 *
 * Copies that family's components into `src/components/icons/` and rewrites
 * `src/components/icons.tsx` so every icon is exported under the name of its
 * role — `CloseIcon`, `SendIcon`, `LightThemeIcon` — rather than its drawing.
 * Call sites never learn which family is in use, so trying another one is:
 *
 *     bun run --cwd packages/ui icons micro
 *
 * The table below is the whole decision: for each role, which drawing each
 * family provides. A family that lacks a drawing for a role gets the closest
 * one it has, chosen by hand and named here so the substitution is visible.
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const LIBRARY = join(homedir(), '.nucleo', 'skills')

/** Component-name suffix each family uses, which also encodes its fill and size. */
const FAMILIES = {
  ui: 'Outline18',
  micro: 'Glyph20',
}

/** Role → drawing, per family. Keep alphabetical by role. */
const ICONS = {
  ArrowLeftIcon: { ui: 'ArrowLeft', micro: 'ArrowLeft' },
  ArrowRightIcon: { ui: 'ArrowRight', micro: 'ArrowRight' },
  BranchIcon: { ui: 'CodeBranch', micro: 'CodeBranch' },
  CheckIcon: { ui: 'Check', micro: 'Check' },
  ChevronDownIcon: { ui: 'ChevronDown', micro: 'ChevronDown' },
  ChevronExpandIcon: { ui: 'ChevronExpandY', micro: 'ChevronExpandY' },
  ChevronRightIcon: { ui: 'ChevronRight', micro: 'ChevronRight' },
  CloseIcon: { ui: 'Xmark', micro: 'Xmark' },
  // micro has no slashed plug; filled against hollow carries the same contrast.
  ConnectedIcon: { ui: 'Plug2', micro: 'PlugFilled' },
  DisconnectedIcon: { ui: 'PlugOff', micro: 'Plug' },
  // micro has no sun or moon; these are its brightness and night-mode glyphs.
  DarkThemeIcon: { ui: 'Moon', micro: 'NightShift' },
  LightThemeIcon: { ui: 'Sun', micro: 'BrightnessIncrease' },
  SystemThemeIcon: { ui: 'Monitor', micro: 'Monitor' },
  DownloadIcon: { ui: 'Download', micro: 'Download' },
  FolderIcon: { ui: 'Folder', micro: 'Folder' },
  MinusIcon: { ui: 'Minus', micro: 'Minus' },
  PlusIcon: { ui: 'Plus', micro: 'Plus' },
  RefreshIcon: { ui: 'Refresh', micro: 'Refresh' },
  RemoteIcon: { ui: 'Laptop', micro: 'Laptop' },
  SearchIcon: { ui: 'Magnifier', micro: 'Magnifier' },
  SendIcon: { ui: 'PaperPlane', micro: 'PaperPlane2' },
  SettingsIcon: { ui: 'Gear', micro: 'Gear' },
  SparkleIcon: { ui: 'Sparkle', micro: 'Sparkle' },
  SwitchIcon: { ui: 'ArrowsOppositeDirectionX', micro: 'ArrowsOppositeDirectionX' },
  TrashIcon: { ui: 'Trash', micro: 'Trash' },
}

const family = process.argv[2]
if (!(family in FAMILIES)) {
  console.error(`usage: nucleo-icons.mjs <${Object.keys(FAMILIES).join('|')}>`)
  process.exit(2)
}
const suffix = FAMILIES[family]
const source = join(LIBRARY, family, 'components')
if (!existsSync(source)) {
  console.error(`no Nucleo library at ${source}`)
  process.exit(1)
}

const here = dirname(fileURLToPath(import.meta.url))
const components = join(here, '..', 'src', 'components')
const target = join(components, 'icons')
rmSync(target, { recursive: true, force: true })
mkdirSync(target)

const lines = [
  '/*',
  ` * Every icon in the product, from one Nucleo family — currently \`${family}\` (${suffix}).`,
  ' *',
  ' * Generated by `scripts/nucleo-icons.mjs`, which copies the components in',
  ' * `./icons/` verbatim from the local Nucleo library and names each by its',
  ' * role. Change the family or a drawing there, not here.',
  ' */',
]
for (const [role, byFamily] of Object.entries(ICONS)) {
  const component = `${byFamily[family]}${suffix}`
  const file = join(source, `${component}.tsx`)
  if (!existsSync(file)) {
    console.error(`${family} has no ${component} for ${role}`)
    process.exit(1)
  }
  copyFileSync(file, join(target, `${component}.tsx`))
  lines.push(`export { ${component} as ${role} } from "./icons/${component}"`)
}
writeFileSync(join(components, 'icons.tsx'), lines.join('\n') + '\n')
console.log(`${family}: ${readdirSync(target).length} icons in place`)
