/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDiffRouteImport } from './routes/_app.diff'
import { Route as AppFileSplatRouteImport } from './routes/_app.file.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDiffRoute = AppDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => AppRoute,
} as any)
const AppFileSplatRoute = AppFileSplatRouteImport.update({
  id: '/file/$',
  path: '/file/$',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diff': typeof AppDiffRoute
  '/file/$': typeof AppFileSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diff': typeof AppDiffRoute
  '/file/$': typeof AppFileSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/diff': typeof AppDiffRoute
  '/_app/file/$': typeof AppFileSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diff' | '/file/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diff' | '/file/$'
  id: '__root__' | '/' | '/_app' | '/_app/diff' | '/_app/file/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/diff': {
      id: '/_app/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof AppDiffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/file/$': {
      id: '/_app/file/$'
      path: '/file/$'
      fullPath: '/file/$'
      preLoaderRoute: typeof AppFileSplatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiffRoute: typeof AppDiffRoute
  AppFileSplatRoute: typeof AppFileSplatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiffRoute: AppDiffRoute,
  AppFileSplatRoute: AppFileSplatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
